server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server #Branch
          uri: https://github.com/ericktrujillo/Microservicios #Repository
          search-paths: config-data #Carpeta
  application:
    name : config-service